### ISSUE TITLE
Image rotate function not work

### ISSUE THREAD

**Issue by dadidzf** [song0071000/unpack_plist_png#1]
https://github.com/song0071000/unpack_plist_png/blob/7f70a77e3bfdd85541aec9f2753b1bd08edfbe16/sample/unpack_plist.py#L55

rect_on_big = rect_on_big.rotate(90) 
Code above can not change the size of the image
We can use
rect_on_big = rect_on_big.transpose(Image.ROTATE_90)   ## This works for me
or
rect_on_big = rect_on_big.rotate(90).resize(height, width)

**Comment by pengsamkee** [comment]
if frame has offset property，it not work well
